
CREATE TABLE Bookings (
  bookingID SERIAL PRIMARY KEY,
  eventID INTEGER NOT NULL,
  userID INTEGER NOT NULL,
  bookingTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (eventID) REFERENCES Events(eventID) ON DELETE CASCADE,
  FOREIGN KEY (userID) REFERENCES Users(userID) ON DELETE CASCADE
);